baseURL = 'https://xert.info/'
languageCode = 'en-us'
title = "Xert's dev log"
theme = 'ash'

[pagination]
  disableAliases = true
  pagerSize = 7
  path = 'page'

[params]
  fontAwesomeURL = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"

  [params.sidebar]
    modules = ["social", "taglist"]

    [[params.sidebar.social]]
      name = "GitHub"
      url  = "https://github.com/XertDev"
      icon = "fab fa-github"
